{"uuid": "6e30d117-4297-4de5-9a4f-be6b7ef3387e", "children": ["0e4ade2d-a1eb-48a1-87b8-0d97be8cb472"], "befores": [{"name": "get_home_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created\nfrom no such window: window was already closed\n  (Session info: chrome=77.0.3865.120)\n\n", "trace": "  File \"c:\\program files\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\program files\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\program files\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\ReservationUITest\\TestCases\\conftest.py\", line 14, in get_home_page\n    driver=DriverClient().get_driver()\n  File \"E:\\ReservationUITest\\Common\\wx_init.py\", line 55, in get_driver\n    self.driver.switch_to.context('WEBVIEW_com.tencent.mm:appbrand0')\n  File \"c:\\program files\\python37\\lib\\site-packages\\appium\\webdriver\\switch_to.py\", line 30, in context\n    self._driver.execute(MobileCommand.SWITCH_TO_CONTEXT, {'name': context_name})\n  File \"c:\\program files\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\program files\\python37\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"c:\\program files\\python37\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"c:\\program files\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1633426892691, "stop": 1633426916140}], "start": 1633426892691, "stop": 1633426916177}